huyvh_app/huyvh_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
router = routers.DefaultRouter()
router.register(r'ws', views.PostViewSet)
urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	#url(r'^blog/', views.index, name='index'),
	url(r'^blog_list/', views.blog_list, name='blog_list'),
    url(r'^search_post/', views.search_post, name='search_post'),
    url(r'^client/', views.blog_client, name='blog_client'),
    url(r'^client_search/', views.blog_client_search, name='blog_client_search'),
    url(r'^searchblog/$', views.get_blog_list),
	#url(r'^$', views.blog_list, name='blog_list'),
	#url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$',views.post_edit, name='post_edit'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  #  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

huyvh_app/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    imgfile = models.FileField(upload_to='files/%Y/%m/%d')
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title

huyvh_app/blog/forms.py
from django import forms
from .models import Post
from django.contrib.admin import widgets
class PostForm(forms.ModelForm):
	#published_date = JqSplitDateTimeField(widget=JqSplitDateTimeWidget(attrs={'date_class':'datepicker','time_class':'timepicker'})	
	class Meta:
       	 model = Post
         fields = ('title', 'text','imgfile','published_date')
	# def __init__(self, *args, **kwargs):
	# 	super(PostForm, self).__init__(*args, **kwargs)
	# 	self.fields['published_date'].widget.attrs['class'] = 'datepicker'

huyvh_app/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponse
from django.utils import timezone
from rest_framework.response import Response
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#define lid for webservice using rest
from rest_framework import viewsets
from .serializers import PostSerializer
from django.core import serializers
from rest_framework.decorators import api_view


QUERY = "search-query"
QUERY_WS = "keywords"
# Create method by Huyvh date 21/082015 using Django FW


# def index(request):
#     return HttpResponse("Hello!")


# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

# get list Blog
def blog_list(request):
        # get all data to DB using view
    #posts = Post.objects.all()
    posts = Post.objects.order_by('-published_date')
    paginator = Paginator(posts, 10) # Show 10 contacts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    #posts =Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    context = {'posts': posts}
    return render(request, 'blog/blog_list.html', context)

 # define using form in Django
def post_new(request):
    if request.method =="POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
           post = form.save(commit=False)
           post.author = request.user
           post.published_date = timezone.now()
           post.imgfile = request.FILES['imgfile']
           post.save()
           return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})
# define post detail
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})
#define post edit
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.imgfile = request.FILES['imgfile']
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})
# define moethod list call ws api
def blog_client(request):
    return render(request, 'blog/post_client.html',  {'' : ''})
# define moethod list call ws api
def blog_client_search(request):
    return render(request, 'blog/post_client_search.html',  {'' : ''})
def search_post(request):
    """List books by a specific author, with optional search"""
    query_string = request.GET.get(QUERY, "").strip()
    print ("######"+query_string)
    posts = Post.objects.filter(title__icontains=query_string).order_by('-published_date')
    paginator = Paginator(posts, 10) # Show 10 contacts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts}
    return render(request, 'blog/blog_list.html', context)
# define methosd publish webservice using REST by HuyVH
class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Post.objects.all().order_by('-published_date')
    serializer_class = PostSerializer
@api_view(['GET', 'POST'])
def get_blog_list(request):
   if request.method == 'GET':
    query_string = request.GET.get(QUERY_WS, "").strip()
    print("########"+query_string)
    posts = Post.objects.filter(title__icontains=query_string).order_by('-published_date')
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)
   elif request.method == 'POST':
    serializer = PostSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST) 

huyvh_app/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html ng-app='MyBlog'>
    <head>
        <meta charset="UTF-8">
        <title>HuyVo Demo Django Frame Work 1.8</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
        <link rel="stylesheet" type="text/css" href="/static/css/coreblog.css"/>
        <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js">
         </script>
         <script src="/static/js/modernizr.js"></script> 
          <script type="text/javascript">
              $(window).load(function(){
                $(".preloader").fadeOut("slow");
          });
          </script>
    </head>
    <body >
    <div class="preloader">
   <div> Đang tải ...<img src="/media/files/image/Preloader_2.gif"/></div>
</div>
    	<h1><a href="/">Blog Project</a></h1>
        <div class="page-header">
            <a href="{% url "post_new" %}" class="top-menu"><span class="glyphicon glyphicon-plus"> </span>Thêm mới</a>
            
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
       
    </body>
</html>

huyvh_app/blog/templates/blog/blog_list.html
{% extends "blog/base.html" %}
{% block content %}
<h1>Tìm kiếm</h1>

<form method="get" action="/search_post/" class="well form-search">
    <p><label for="id_search-query">Lọc:</label>
    <input type="text" name="search-query" id="id_search-query"  placeholder="Tiêu đề..." autofocus />
    <input type="submit" value="Tìm kiếm">
</form>
    <div class="table-responsive">
           <span><a href="/client" class="mct_whatsapp_btns"> call API WS </a></span>
            <span style="margin-left: 10px;"><a href="/client_search" class="mct_whatsapp_btns"> search API WS </a></span>
           <table class="table table-hover">
            <thead>
           	<tr>
           		<th class="col-sm-1">
           		  Tiêu đề
           		</th>
              <th class="col-sm-1">
                Hình ảnh
              </th>
           		<th class="col-sm-6">
           		  Nội dung
           		</th>
           		<th class="col-sm-1">
           		  Ngày xuất bản
           		</th>
              <th class="col-sm-1">
                Share
              </th>
           	</tr>
           	</thead>
           	<tbody>
           	  {% for post in posts %}
           		<tr>              
           		<td>
           		  <p><a href="{% url "post_detail" pk=post.pk %}">{{ post.title }}</a></p>
           		</td>
              <td>
               <a href="{% url "post_detail" pk=post.pk %}"> <img src="{{ post.imgfile.url }}" alt="{{ post.imgfile.name }}" class="img-responsive" width="100" height="120" title="{{ post.imgfile.name }}" /></a>
              </td>
           		<td>
           		 <p>{{ post.text}}</p>  
           		</td>
           		<td>
           		 <p> 
           		 {{ post.published_date|date:"d/m/Y H:m:s" }}
           		 </p>      
           		</td> 
              <td>
              <div class="row">
                
                  <a href="#" data-text="{{ post.text}}" data-link="{% url "post_detail" pk=post.pk %}" class="mct_whatsapp_btn">Share</a>
                
              </div>
              </td>          		
           	</tr>
           	{% endfor %}
           	</tbody>
           </table>
           <!-- phan trang-->
            <ul class="pager">
				    
				        {% if posts.has_previous %}
                 <li class="previous">
				            <a href="?page={{ posts.previous_page_number }}">&larr; Trước</a>
                    </li>
                    {% else %}
        <li class="previous disabled prev"><a href="#">&lsaquo;&lsaquo;</a></li>
				        {% endif %}
                {% for i in posts.paginator.page_range %}
                 <li {% if posts.number == i %} class="active" {% endif %}><a   href="?page={{i}}">{{i}}</a></li>

                {% endfor %}
				        <li>
				            Trang {{ posts.number }} / {{ posts.paginator.num_pages }}.
				        </li>
				        {% if posts.has_next %}
                <li class="next">
				            <a href="?page={{ posts.next_page_number }}">Tiếp theo &rarr;</a>
                    </li>
                    {% else %}
          <li class="next disabled"><a href="#">&rsaquo;&rsaquo;</a></li>
				        {% endif %}
				    
		       </ul>

        <ul class="pagination pagination-centered">
            {% if page_obj.has_previous %}
                <li><a href="?page=1"><<</a></li>
                <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
            {% endif %}
        </ul>
    
            <!-- ket thuc-->
      </div>  
      <!--Demo Share content using Whatapps--> 

<script type="text/javascript">
$(document).ready(function() {
    $(document).on("click", '.mct_whatsapp_btn', function() {
        if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
            var text = $(this).attr("data-text");
            var url = $(this).attr("data-link");
            var message = encodeURIComponent(text) + " - " + encodeURIComponent(url);
            var whatsapp_url = "whatsapp://send?text=" + message;
            window.location.href = whatsapp_url;
        } else {
           var okie= confirm('Bạn có muốn share lên Whatsapp ?') 
           if (okie) {
              var text = $(this).attr("data-text");
              var url = $(this).attr("data-link");
              var message = encodeURIComponent(text) + " - " + encodeURIComponent(url);
              var whatsapp_url = "whatsapp://send?text=" + message;
              window.location.href = whatsapp_url;
            } else {
                alert ('Thanks');
            }
        }
    });
});
</script>
{% endblock %}

huyvh_app/blog/templates/blog/post_client.html
 {% extends "blog/base.html" %}
     
 {% block content %}
        <span> <a href="{% url "blog_list" %}"> List Post </a></span>
        {% load static %}
        <script src="{% static "js/angular.min.js" %} " type="text/javascript"></script>
       <script src="{% static "js/clientAPI.js" %} " type="text/javascript"></script>
   
       <!--using verbatim de phan biet bien angulajs va bien cua django fw-->
        {% verbatim %}
        <div ng-controller='callWSCtl'>
        <table class="table table-hover">
            <thead>
            <tr>
                <th class="col-sm-1">
                  Tiêu đề
                </th>
              <th class="col-sm-1">
                Hình
              </th>
                <th class="col-sm-6">
                  Nội dung
                </th>
                <th class="col-sm-1">
                  Ngày xuất bản
                </th>
            </tr>
            </thead>
            <tbody ng-repeat='result in Arrhuyvh'>
                <tr>
                <td>
                  <p>{{ result.title }}</p>
                </td>
              <td>
                <img src="{{ result.imgfile }}" alt="{{ result.imgfile.name }}" class="img-rounded" width="100" height="120" />
              </td>
                <td>
                 <p>{{ result.text}}</p>  
                </td>
                <td>
                 <p> 
                 {{ result.published_date | date:'dd/MM/yyyy HH:mm:ss' }}
                 </p>      
                </td>                   
            </tr>          
            </tbody>
           </table>
           </div>
        {% endverbatim %}
        {% endblock %}

huyvh_app/blog/templates/blog/post_client_search.html
 {% extends "blog/base.html" %}     
 {% block content %}
        {% load static %}
        <script src="{% static "js/angular.min.js" %} " type="text/javascript"></script>
     <script src="{% static "js/searchAPI.js" %} " type="text/javascript"></script>
       <!--using verbatim de phan biet bien angulajs va bien cua django fw-->
        {% verbatim %}
        <!-- Block search API-->
        <div ng-controller="SearchCtrl">

          <h1>Tìm kiếm</h1>         
          <form class="well form-search">
            <label>Lọc:</label>
            <input type="text" ng-model="keywords" class="input-medium search-query" placeholder="Tiêu đề..." ng-enter="search()" autofocus/>
            <button  type="submit" class="btn" ng-click="search()" >
            Tìm kiếm
            </button>
            </form>
           <!-- <pre ng-model="Arrhuyvh">
              {{Arrhuyvh}}
            </pre>-->
               {% endverbatim %}
            <span> <a href="{% url "blog_list" %}" class="mct_whatsapp_btns"> Back List Post </a></span>
            
       {% verbatim %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th class="col-sm-1">
                  Tiêu đề
                </th>
              <th class="col-sm-1">
                Hình
              </th>
                <th class="col-sm-6">
                  Nội dung
                </th>
                <th class="col-sm-1">
                  Ngày xuất bản
                </th>
            </tr>
            </thead>
            <tbody ng-repeat='result in Arrhuyvh'>
                <tr>
                <td>
                  <p>{{ result.title }}</p>
                </td>
              <td>
                <img src="{{ result.imgfile }}" alt="{{ result.imgfile.name }}" class="img-rounded" width="100" height="120" />
              </td>
                <td>
                 <p>{{ result.text}}</p>  
                </td>
                <td>
                 <p> 
                 {{ result.published_date | date:'dd/MM/yyyy HH:mm:ss' }}
                 </p>      
                </td>                   
            </tr>          
            </tbody>
           </table>
           </div>
        {% endverbatim %}
        {% endblock %}

huyvh_app/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="post">
       
        <a class="btn btn-default" href="{% url "post_edit" pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a><br/>
        <p>
        <img src="{{ post.imgfile.url }}" alt="{{ post.imgfile.name }}" class="img-rounded" width="100" height="120" title="{{ post.imgfile.name }}" />
        </p>
        <p><h1 style="float: left">{{ post.title }} </h1> {% if post.published_date %}
            <div class="date">
                <span> -{{ post.published_date }}</span>
            </div>
        {% endif %} </p>
        <p>{{ post.text|linebreaks }}</p>

        <a class="btn btn-default" href="{% url "blog_list" %}">
        Quay lại 
        </a>
    </div>
{% endblock %}

huyvh_app/blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

{% block content %}
    
    <form method="POST" class="post-form" enctype="multipart/form-data">
       {% csrf_token %}
        {% if form.errors %}
    <div class="text-danger">Vui lòng nhập thông tin hợp lệ {{ form.errors|pluralize }} bên dưới.</div>
    {% endif %}

     <div class="form-group row {% if form.title.errors %}has-error{% endif %}">
           <label for="id_title" class="col-sm-3 control-label">Tiêu đề</label>
            <div class="col-lg-5">
            {{ form.title }}
            {% if form.title.errors %}
              <span class="help-block">
                {% for error in form.title.errors %}({{ error }}){% endfor %}
              </span>
            {% endif %}
     		</div>
     </div>
   	 <div class="form-group row {% if form.text.errors %}has-error{% endif %}">
           <label for="id_text" class="col-sm-3 control-label">Nội dung</label>
      <div class="col-lg-5">
            {{ form.text }}
            {% if form.text.errors %}
              <span class="help-block">
                {% for error in form.text.errors %}({{ error }}){% endfor %}
              </span>
            {% endif %}
     </div>
     </div>
      <div class="form-group row">
           <label for="id_imgfile" class="col-sm-3 control-label">Hình đại diện</label>
      <div class="col-lg-5">
      {# <img src="{{ form.instance.imgfile.url }}" alt="{{ form.instance.imgfile.name }}" class="img-responsive" width="100" height="120" title="{{ form.instance.imgfile.name }}" /> #}
            {{ form.imgfile }}
     </div>
     </div>
      <div class="form-group row">
           <label for="id_published_date" class="col-sm-3 control-label">Ngày xuất bản</label>
	      <div class="col-lg-5">
	            {{ form.published_date }}
	     </div>
     </div>
        {# {{ form.as_p }}  #}
         <div class="form-group row">
          <div class="col-sm-5 col-sm-offset-3">
          		<button type="submit" class="save btn btn-default">Lưu</button>
		         <a class="btn btn-default" href="{% url "blog_list" %}">
		        Quay lại       
		        </a>
          </div>
        </div>        
    </form>
{% endblock %}